- name: Generate lines from template
  set_fact:
    host_lines: |
      {{ groups['minio01'][0] }} test1
      {{ groups['minio_others01'][0] }} test2
      {{ groups['minio_others02'][0] }} test3
      {{ groups['minio_others03'][0] }} test4

- name: "Add lines to /etc/hosts"
  lineinfile:
    path: "/etc/hosts"
    line: "{{ item }}"
    state: present
  loop: "{{ host_lines.split('\n') }}"